### ISSUE TITLE
Allow main site to toggle back and forth between English and Spanish multiple times

### ISSUE THREAD

**Issue by laurennc** [lsst-epo/rubin-obs-client#113]
## Expected Behavior
On the homepage, switching between locales should be seamless and infinitely togglable

## Actual Behavior
On the homepage, switching between locales more than once results in 404 and then js error in the console.  Seems like this only affects the homepage

[Screengrab of the issue](https://www.dropbox.com/s/yc8t0d9f5jsfkh8/Screen%20Recording%202022-03-18%20at%209.44.55%20AM.mov?dl=0)

## Steps to Reproduce the Problem

1. Go to [the homepage](https://rubinobs.com)
2. Click on the locale toggle button
3. Observe it switches contents' language and updates the url
4. Click on the locale toggle button again
5. Observe it 404s but url updates correctly
6. Click on the locale toggle button again
7. Observe js errors in the console

**Comment by blnkt** [comment]
Huh.  Yea, I'm seeing this issue in [integration](https://int.rubinobs.com/) and [prod](https://rubinobs.com/).  You're right, [dev](https://dev.rubinobs.com/) seems fine.  Interesting...  Both `prod` and `integration` has `rubin-obs-client` up to date with `develop`, and `rubin-obs-api` is quite nearly up to date with `develop`.  I have not tested locally.  Testing in Firefox 98.0.1 and Chrome 99.0.  Odd...

**Comment by dananjohnson** [comment]
Interesting. Yeah I see it too on integration and prod, so I'll start there and see if I can sort it out.
