### ISSUE TITLE
Gallery Item page breadcrumb root should be "Gallery"

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#115]
Feels like it could be related to #8, #19, and/or #116  

## Expected Behavior
Expect Gallery to be the root of breadcrumb for Gallery Item pages

## Actual Behavior
Root of breadcrumb is "Slideshows"

## Steps to Reproduce the Problem

1. Go to [any Gallery Item page](https://rubinobs.com/gallery/big-camera-big-lens)
2. Observe the breadcrumb shows "Slideshows" as the root
3. Click on "Slideshows".  It goes to the slideshows filtered gallery page. 

https://user-images.githubusercontent.com/8166060/159043851-9e2904a9-d9d4-4474-9e1d-b935cfb90b70.mov

**Comment by jen-castiron** [comment]
@blnkt Is this still an issue, or should the status be changed to Done?

**Comment by blnkt** [comment]
@jen-castiron As far as I know it's still an issue.  Just checked dev.rubinobs.com
<img width="1139" alt="Screen Shot 2022-03-22 at 4 07 23 PM" src="https://user-images.githubusercontent.com/8166060/159590981-439fc12b-1636-49f2-a061-2297e6326c50.png">

**Comment by dananjohnson** [comment]
@blnkt this can be resolved in the backend by changing the entry corresponding to the header "Gallery": https://api-dev.rubinobs.com/admin/globals/default/rootPageInformation. Note that it's currently set to the Slideshows page.
