### ISSUE TITLE
"Images" links on Gallery Item pages should link to "Images" Gallery page

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#116]
Feels like it could be related to #8, #19, and/or #115 

## Expected Behavior
Expect "Back to Images" link and "Images" link in the breadcrumb to link to a pre-filtered Gallery page that's just images

## Actual Behavior
"Images" links on Gallery Item pages 404

https://user-images.githubusercontent.com/8166060/159044480-e8fa2ad6-28a5-4efa-a4a5-5f5113979043.mov

## Steps to Reproduce the Problem

1. Go to [any Gallery Item page](https://rubinobs.com/gallery/big-camera-big-lens)
2. Click on the breadcrumb "Images" link
3. Observe it 404s
4. Go back to the Gallery Item page
5. Click on the "Back to Images" link at the bottom of the page
6. Observe it 404s

**Comment by jen-castiron** [comment]
@blnkt Same with this issue - should the status be changed to Done?

**Comment by blnkt** [comment]
@jen-castiron ditto, as far as I can tell this is still an issue.  Just checked dev.rubinobs.com and is 404ing.  I have not tested locally.

**Comment by jen-castiron** [comment]
@blnkt Got it! I'll check it out today 👀
