### ISSUE TITLE
Tighten up whitespace between page heading and first paragraph; page heading and social links

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#16]
## Request
Reduce by about half the padding between page heading and first paragraph; page heading and the social links; social links and first paragraph (all sections?).  Jose to indicate precisely how much padding (either through updated design or as # of pixels).

## Currently
So much whitespace.

**Comment by jen-castiron** [comment]
@blnkt , is this for the RTE content, or the site content? Looking at the design docs, I'm not sure which areas need to be fixed.

**Comment by jen-castiron** [comment]
@blnkt Nevermind - Dana pointed out the `20220112 Website updates and requirements for CIC -  Read me.pdf`. This looks like it also relates to #18
