### ISSUE TITLE
Support for creating gallery pages for any CMS defined "Gallery Type"

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#19]
Feels like it could be related to #8, #116, and/or #115 

## Request
The ability to create type-specific gallery pages from any of the types as they appear in the filters dropdown.  E.g. being able to include direct link in the main nav to an "Images" gallery page and a "videos" gallery page.

## Currently
Currently only supports "all" and "slideshows".

**Comment by blnkt** [comment]
Elevating the priority of this feature after receiving new feedback from content creator colleagues.

**Comment by kylepratuch** [comment]
@blnkt Does this refer to the options listed in the `Dynamic Component` field on Page entries?

**Comment by blnkt** [comment]
@kylepratuch Bingo.  Yahtzee.  Yes.
