### ISSUE TITLE
Mobile menu should collapse when navigating between pages

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#192]
## Expected Behavior
When the mobile Main Nav is expanded and the User navigates to another page, the mobile Main Nav collapses.

## Actual Behavior
When the mobile Main Nav is expanded, and the user navigates to another page, navigation is successful, but the Main Nav remains expanded.

## Steps to Reproduce the Problem

1.  Make window < 1500px wide
2. Expand the mobile Main Nav
3. Click on one of the links in the mobile Main Nav
4. Observe the page redirects to wherever
5. Observe the mobile Main Nav remains expanded

**Comment by blnkt** [comment]
Oh interesting, it looks like it may only be when navigating between interior pages.  So scrunch down your browser window so it's narrow, go to https://dev.rubinobs.com/explore/rubin-science-goals, and then open the mobile main nav and click on "Key Numbers"  (https://dev.rubinobs.com/explore/key-numbers) and I think you'll find the nav does not close.

**Comment by dananjohnson** [comment]
@blnkt hmm maybe it's fixed now? I recall being able to reproduce this a few months ago per your last comment, but now I can't.

**Comment by blnkt** [comment]
I'll try to reproduce today and let you know if is still a thing

**Comment by blnkt** [comment]
Agreed.  Cannot reproduce.  Closing.
