### ISSUE TITLE
Add "Flexible" table cells option

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#195]
## Request
Flexible table cells option that would have table cells resize to conform to cell contents.  Aplied at the level of the row so that `<th>` could be excluded?  Accomplished by applying `white-space: nowrap` to cells?

## Currently
All cells are of equal width.

**Comment by dananjohnson** [comment]
@blnkt I set up a demo page with the existing table blocks to help me visualize this: https://dev.rubinobs.com/for-educators/tables-demo. Did you kinda have the third table ("NGSS Scoring Table") in mind when suggesting this option? I'm sure we could add an option in the CMS to disable white-space wrapping on any cell if that would solve your situation.

**Comment by blnkt** [comment]
> I'm sure we could add an option in the CMS to disable white-space wrapping on any cell if that would solve your situation.

yea lets try this and hopefully that's enough flexibility for our content creators to affect the kind of layouts they're after.

**Comment by dananjohnson** [comment]
Great. @kylepratuch can you proceed with this?

**Comment by kylepratuch** [comment]
Try this on, @dananjohnson: https://github.com/lsst-epo/rubin-obs-api/pull/105
