### ISSUE TITLE
Events have start and end dates

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#20]
## Request
Event can have end date.  Shows end date in Events listing and Event single.  Updated design to be supplied by Jose.

## Currently
Currently only start dates.

**Comment by jen-castiron** [comment]
Hi @blnkt! Who do I reach out to for adding an end date to the events model? 
<img width="670" alt="Screen Shot 2022-02-21 at 10 42 44 AM" src="https://user-images.githubusercontent.com/57107444/155011343-b1a61565-11f4-4289-8138-3abf7c6b1f00.png">

**Comment by blnkt** [comment]
CIC is handling both the frontend and backend updates, so whoever on your team.  @lthurston can advise.
