### ISSUE TITLE
404 error on gallery item page load

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#25]
<img width="400" alt="Screen Shot 2021-12-27 at 4 28 17 PM" src="https://user-images.githubusercontent.com/8166060/147515530-029e8b94-5050-49ed-b9c6-b09ba705e5b3.png">

## CIC Estimate
1 point

**Comment by dananjohnson** [comment]
I'm not able to reproduce this locally. Once dev.rubinobs is working correctly, let's check there to see if this is still an issue.

**Comment by blnkt** [comment]
Can no longer reproduce.  closing as hopefully is a non-issue
