### ISSUE TITLE
401 error on all pages after initial page load

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#26]
## Steps to Reproduce the Problem

1.  Visit any page (including the homepage) with the devTools open
2. Wait for page to load
3. Wait a couple more seconds after that and error will appear in console + network tab
<img width="400" alt="Screen Shot 2021-12-27 at 4 27 59 PM" src="https://user-images.githubusercontent.com/8166060/147515610-8fe1ade5-4909-4337-9ab5-683e82a75db8.png">

## CIC Estimate
0 points

**Comment by dananjohnson** [comment]
@blnkt I can't reproduce this locally. The file that's getting 401'd is `site.webmanifest`, which lives [here](https://github.com/lsst-epo/rubin-obs-client/blob/master/public/site.webmanifest) in the repo. Access should just work, as it does with the various favicon files in that folder. If a 401 is being thrown, is there a perhaps a configuration issue on the server?

**Comment by blnkt** [comment]
Looks like the issue was only on digital ocean.  I can't reproduce locally or in GCP instances.
