### ISSUE TITLE
Full site search should yield results

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#31]
## Expected Behavior
Search results page should list all relevant results based on search term.

## Actual Behavior
Searching an "I'm pretty sure this search term appears at least once on the site" yields no results.
<img width="400" alt="Screen Shot 2021-12-28 at 8 49 21 AM" src="https://user-images.githubusercontent.com/8166060/147588900-688655d3-af7b-401d-b73f-4aeb91e97403.png">
<img width="400" alt="Screen Shot 2021-12-28 at 8 51 12 AM" src="https://user-images.githubusercontent.com/8166060/147588948-e93f8115-6539-48e2-816d-34d09e58646e.png">

**Comment by jen-castiron** [comment]
@blnkt This is another setting in Craft:
1. Go to Entries -> Singles
2. Open "Search Results"
3. Set "Dynamic Component" to "Search"
I've already set this in the Development & Integration APIs 👍
