### ISSUE TITLE
Ensure active user interface components have sufficient contrast

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#56]
Related to #53 

## Description
Visual details needed to identify active user interface controls and their states including, but not limited to, buttons, form fields and focus and selected state indicators of these controls need to have a contrast ratio of at least 3:1 contrast with adjacent colors. This requirement is necessary to ensure that identifying features of controls and states (non-text) are distinguishable by people with low vision. Low contrast controls are more difficult to perceive and may be completely missed by people with a visual impairment.

Any parts of controls that identify the control need to have sufficient contrast with the adjacent background. In practice, this means that not all parts of a control must have sufficient contrast. For example, if an input has a shaded background and a bottom border line, it may only be necessary to ensure that the bottom line has sufficient contrast.

In addition, the indicators of states (hover, focused, checked, selected, current item, etc., when present) need to also provide the minimum 3:1 contrast with the colors adjacent to the control.

### SlideBlock controls
 - [x] **[SEE COMMENT FOR UPDATED DESIGN](https://github.com/lsst-epo/rubin-obs-client/issues/56#issuecomment-1050363373)** Active (hover/focus) state should meet minimum contrast of 3:1.  Current contrast ratio is 1.5:1

![0f43586f1c3193acec46249844767fd7eb303066-1641299900](https://user-images.githubusercontent.com/8166060/152615519-dd820df6-aa81-4cdb-a4ad-baa64da75b95.png)

**Comment by dananjohnson** [comment]
@blnkt any updates on design changes?

**Comment by blnkt** [comment]
@dananjohnson Jose has tickets to update design for some accessibility stuff, including the slider stuff, this sprint. So we should see those new designs by Wednesday 3/2.

**Comment by dananjohnson** [comment]
Sounds great. Thanks!

**Comment by blnkt** [comment]
For **SlideBlock controls**

[This is a dropbox link for updated design for desktop controls hover & focus states](https://www.dropbox.com/s/owakayf7dh012jm/20220223%20Focus%20is%20indicated%20visually.pdf?dl=0) (use the same style for both states).

**Comment by blnkt** [comment]
And so I think this issue is no longer blocked.
