### ISSUE TITLE
Ensure custom controls provide proper textual name, role, and state information

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#59]
## Description
At a basic level, all custom controls within a web application should provide identifying information about the component. This includes a name, type (role) and may contain state, value, and description information (applicable).

When custom elements do not expose identifying information, users of assistive technology may not be able to identify and interact with the element. For example, without knowing the role or state of an element, the user of a screen reader may not know what actions can be performed on an element even if the element exposes a textual name. Without a proper role, assistive technology interactions that rely on roles being identified may not become available to the user.

### Breadcrumb

- [x] Active breadcrumb link should state its state

![40c03503e9444e8efef881e023552b362bf19970-1641199159](https://user-images.githubusercontent.com/8166060/152618988-206aaaec-b504-4302-aabd-9cb2740830c9.png)

#### Compliant Code Example
State: `aria-current="true"` for currently active link

```
<li class="Breadcrumbs__Item-sc-1p78jzo-4 jHzYOJ"><a href="/about/supporters-and-participants/science-collaborations" class=""  aria-current="true">Vera C. Rubin Observatory science collaborations</a></li>
```

### Accordions

- [ ] Accordion control should communicate name, state, and role. It is suggested first that native HTML elements be utilized as they will automatically have these attributes built in. It is recommended to use a native <button> element instead of <summary> and <details>.  [More information about creating accessible accordions can be found on the W3C website](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html).

![8ed77cfda8c7fe6613e2b1ea59727218eb13acd2-1641195381](https://user-images.githubusercontent.com/8166060/152619384-d8c1d62c-c290-42ad-8f53-9d58d3af23ea.png)

**Comment by dananjohnson** [comment]
I've fixed the breadcrumbs. I don't think we need to do anything about the accordions, as they are already using the HTML `details` element (see issue screenshot).

**Comment by blnkt** [comment]
@dananjohnson from the LevelAccess feedback:

> [Issue]
> The accordion control available below the headings 'For scientists in the project or wanting to get involved:', 'Rubin Observatory structure and management:', 'Rubin Observatory data products and publications:' are announced as buttons and also convey the state information. However, these controls are not programmatically coded using button element. Additionally the screen reader users will not be able to pull the list of buttons using short cut Keys.
> 
> 
> [User Impact]
> When controls do not provide name, role and/or state, screen reader users will not know their purpose and current state (if applicable).
>
> [Recommendation]
> Ensure that all controls communicate name, state, and role. It is suggested first that native HTML elements be utilized as they will automatically have these attributes built in. It is recommended to use a native `<button>` element instead of `<summary>` and `<details>`

so I think taking a second look at the [w3 example](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html) they linked to (if you haven't already), as well as the [accordion design pattern](https://www.w3.org/TR/wai-aria-practices/#accordion) linked to in that w3 info, and if you feel like what we've got satisfies the goal of having the accordions "announce" their function and state as expected, well then great!

**Comment by dananjohnson** [comment]
@blnkt to the best of my understanding, the implementation communicates name, state, and role, as shown in the screenshot. Granted, it's only one screen reader (VoiceOver), but I'd expect using `details` and `summary` here to be a reliable solution. Those examples you shared look to me like how you'd go about it if you weren't using `details` and `summary` and needed to implement name, role, and state using ARIA attributes instead. All that said, I'd be very curious if there's a reason LevelAccess doesn't recommend using `details` and `summary` for collapsible content. I've always just assumed that was the way to do it!

<img width="1141" alt="Screen Shot 2022-02-21 at 2 25 00 PM" src="https://user-images.githubusercontent.com/12454203/155034416-92d9f797-5e73-42e1-a691-e72b10ac33ba.png">

**Comment by dananjohnson** [comment]
Follow up: I do see one small issue here, which is that the "plus" icon is implemented as a CSS pseudo-element, so some screen readers read out the "plus". I'm gonna revise it to use SVG with `role="presentation"` instead.
