### ISSUE TITLE
Provide fieldsets for groups of form controls

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#69]
## Description
Forms should utilize the `fieldset` and `legend` elements to group related form controls. For example, on an order form, authors should separate categories such as "Billing Information", "Shipping Address", and "Order Summary" using fieldset elements. By grouping all of the elements in one category users of assistive technologies can understand the relationship of the elements. For example, without proper grouping a person using a screen reader might not be able to differentiate the address field for shipping from the address field for billing. Another example is when radio buttons are used as answers and a question appears above or to the left of the radio buttons. When the question text and radio buttons are not properly constructed in a fieldset users of screen readers may only be aware of the answers and not the question.
### Header
- [x] Language Toggle should use "Language" in the legend, instead of "Localize site content."  And should double as the toogle's label?

![c8b1d9b01ae7c448c3dfefa8d8adc447297fe6c0-1641469724](https://user-images.githubusercontent.com/8166060/153071240-8939429d-cdfa-485a-a062-9a5310b20edb.png)

**Comment by dananjohnson** [comment]
Resolved by https://github.com/lsst-epo/rubin-obs-client/commit/cf360cff94618817455071707633d74afe6e6783.
