### ISSUE TITLE
Tag links in News articles 404

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/rubin-obs-client#8]
## Expected Behavior
Tag should link to news search results page with same results as you would find if you manually searched the tag term in the sort/filter/search bar.

## Actual Behavior
404 page not found.

## Steps to Reproduce the Problem

1. Go to [Collision of Neutron Stars Caught in the Act](https://staging.rubinobs.org/news/collision-of-neutron-stars-caught-in-he-act )
2. Click on `neutron star` link
3. Redirects to `https://staging.rubinobs.org/undefined?search=neutron-star ` (note undefined value)
<img width="400" alt="Screen Shot 2021-12-16 at 9 06 13 AM" src="https://user-images.githubusercontent.com/8166060/146417646-7692296e-5d4b-43e1-9582-8cb4f1323a06.png">

For comparison:
1. Go to [News page](https://staging.rubinobs.org/news) and search `neutron star`
2. Redirects to `https://staging.rubinobs.org/news?search=neutron+star`
<img width="400" alt="Screen Shot 2021-12-16 at 9 07 49 AM" src="https://user-images.githubusercontent.com/8166060/146417744-adcdc1fc-0329-4d39-a807-3c67f2ccdda8.png">

**Comment by jen-castiron** [comment]
Hey @blnkt , it looks like this one is an API issue. To get the links to work, "News" needs to be set as a root page in craft: https://rubin-obs-api-int-2eici5myiq-uc.a.run.app/admin/globals/default/rootPageInformation The front-end is looking for "News" in that list of root pages, and then getting the news uri from that data. 

Where the news page is getting breadcrumb data:
https://github.com/lsst-epo/rubin-obs-client/blob/master/components/templates/NewsPage/index.js#L45

The `useCustomBreadcrumbs` function, which looks for root pages:
https://github.com/lsst-epo/rubin-obs-client/blob/master/lib/utils.js#L87-L93

There's a few places in the code where this hook is looking for root values, and they're not defined in Craft either:
* StaffPage.jsx, "Staff Profiles"
* EventPage.jsx, "Events"
* SlideshowPage.jsx, "Slideshows"

Is there any reason _not_ to add these pages to the global root page information?

**Comment by blnkt** [comment]
No that sounds like a fine solution, makes sense now that you've explained it.  I think that functionality was never very clear to us so our Content Editors probably just didn't know to make the change in that Globals section.  I'll give it a go and watch the magic happen.

**Comment by blnkt** [comment]
works just as you say.  Thank you much.
